# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 02:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20160216_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apross',
            name='date',
        ),
        migrations.AddField(
            model_name='apross',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2016, 2, 17, 2, 21, 45, 912808, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apross',
            name='month',
            field=models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), ('12', 'Diciembre')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apross',
            name='year',
            field=models.PositiveIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
