# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 04:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160217_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='apross',
            name='real_date',
            field=models.DateField(default=datetime.datetime(2016, 2, 17, 4, 55, 19, 721808, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apross',
            name='month',
            field=models.CharField(choices=[('enero', 1), ('febrero', 2), ('marzo', 3), ('abril', 4), ('mayo', 5), ('junio', 6), ('julio', 7), ('agosto', 8), ('septiembre', 9), ('octubre', 10), ('noviembre', 11), ('diciembre', 12)], max_length=15),
        ),
    ]
