# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_auto_20160220_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faces',
            name='initial',
            field=models.CharField(max_length=250),
        ),
    ]
