# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20160220_0105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faces',
            options={'verbose_name': 'Cara', 'verbose_name_plural': 'Caras'},
        ),
        migrations.AlterField(
            model_name='detailapross',
            name='day',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
