# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_auto_20160220_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailapross',
            name='faces',
            field=models.ManyToManyField(blank=True, to='register.Faces'),
        ),
    ]
