# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0010_auto_20160220_0235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailapross',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
