# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-09 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0019_auto_20160227_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailapross',
            name='practic_code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='detailbenefit',
            name='code',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
