# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0039_auto_20160419_2232'),
        ('register', '0026_auto_20160405_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('treatment', models.CharField(blank=True, max_length=25, null=True)),
                ('tooth', models.IntegerField(blank=True, choices=[(11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85)], null=True)),
                ('period_so', models.CharField(blank=True, max_length=30, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('faces', models.ManyToManyField(blank=True, to='register.Faces')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Patient')),
            ],
        ),
    ]
