# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0027_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='assistance',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='record',
            name='state2',
            field=models.SmallIntegerField(default=3),
        ),
    ]
