# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-28 16:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_auto_20160428_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='state',
        ),
    ]
