# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_auto_20160428_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'Realizado'), (2, 'Por Terminar'), (3, 'A realizar')], default=1),
        ),
    ]
