# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-13 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_auto_20160429_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='debit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='havings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
    ]
