# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-19 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_auto_20160518_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='debit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='record',
            name='havings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
    ]
