# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0038_auto_20160530_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='to_account',
            field=models.BooleanField(default=True),
        ),
    ]
