# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_record_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='to_social_work',
            field=models.BooleanField(default=True),
        ),
    ]
