# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-28 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0040_record_to_social_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='apross',
            name='printed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='benefit',
            name='printed',
            field=models.BooleanField(default=False),
        ),
    ]
