# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-05 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160902_1745'),
        ('register', '0041_auto_20160727_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Tariff'),
        ),
    ]
