# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0054_auto_20160906_1711'),
        ('register', '0042_record_tariff'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('debit', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('havings', models.DecimalField(decimal_places=0, default=0, max_digits=7)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Patient')),
                ('record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Record')),
            ],
        ),
    ]
