# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_currentaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentaccount',
            name='observations',
        ),
    ]
