# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('notes', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('circle', models.IntegerField()),
                ('register_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('second_name', models.CharField(blank=True, max_length=250, null=True)),
                ('last_name', models.CharField(blank=True, max_length=250, null=True)),
                ('subsidiary_number', models.PositiveIntegerField(unique=True)),
                ('clinic_history', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Clinic_history')),
                ('dentist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Dentist')),
            ],
        ),
    ]
