# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dentist',
            name='second_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='second_name',
        ),
    ]
