# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 05:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_auto_20160214_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dentist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Dentist'),
        ),
    ]
