# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_auto_20160214_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.AddField(
            model_name='patient',
            name='reciently_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subsidiary_number',
            field=models.PositiveIntegerField(unique=True, verbose_name='numero de afiliado'),
        ),
    ]
