# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-14 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0005_auto_20160214_0517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='reciently_added',
        ),
    ]
