# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0011_auto_20160215_2001'),
    ]

    operations = [
        migrations.AddField(
            model_name='dentist',
            name='carrying_home',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
