# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0015_auto_20160221_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialWork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('initial', models.CharField(max_length=250)),
            ],
        ),
    ]
