# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 06:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0016_socialwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SocialWork',
        ),
    ]
