# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0019_auto_20160222_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='social_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.SocialWork'),
        ),
    ]
