# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0020_auto_20160222_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='social_work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.SocialWork'),
        ),
    ]
