# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0023_auto_20160227_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='register_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='subsidiary_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='numero de afiliado'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
