# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0024_auto_20160227_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='subsidiary_number',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='numero de afiliado'),
        ),
    ]
