# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0025_auto_20160227_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='register_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tel',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
