# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0027_auto_20160228_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odontogram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teeth_number', models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32)], null=True)),
                ('observations', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.SmallIntegerField(choices=[(1, 'C'), (2, 'T'), (3, 'B'), (4, 'R'), (5, 'L')])),
                ('color', models.SmallIntegerField(blank=True, choices=[(1, 'red'), (2, 'blue')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(choices=[(11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36), (37, 37), (38, 38), (41, 41), (42, 42), (43, 43), (44, 44), (45, 45), (46, 46), (47, 47), (48, 48), (51, 51), (52, 52), (53, 53), (54, 54), (55, 55), (61, 61), (62, 62), (63, 63), (64, 64), (65, 65), (71, 71), (72, 72), (73, 73), (74, 74), (75, 75), (81, 81), (82, 82), (83, 83), (84, 84), (85, 85)])),
                ('color', models.SmallIntegerField(blank=True, choices=[(1, 'red'), (2, 'blue')], null=True)),
                ('work_type', models.SmallIntegerField(blank=True, choices=[(1, 'Extraccion'), (2, 'Endodoncia'), (3, 'Restauracion'), (4, 'Restauracion filtrada'), (5, 'Caries'), (6, 'Corona')], null=True)),
                ('odontogram', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Odontogram')),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='tooth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.Tooth'),
        ),
        migrations.AddField(
            model_name='patient',
            name='odontogram',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.Odontogram'),
        ),
    ]
