# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0028_auto_20160229_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='points',
            field=models.SmallIntegerField(blank=True, choices=[(1, '5,5    15,5    15,15   5,15'), (2, '0,0    20,0    15,5    5,5'), (3, '5,15   15,15   20,20   0,20'), (4, '15,5   20,0    20,20   15,15'), (5, '0,0    5,5     5,15    0,20')], null=True),
        ),
        migrations.AddField(
            model_name='tooth',
            name='position_x',
            field=models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 25), (2, 50), (3, 75), (4, 100), (5, 125), (6, 150), (7, 175), (8, 210), (9, 235), (10, 260), (11, 285), (12, 310), (13, 335), (14, 360), (15, 385)], null=True),
        ),
        migrations.AddField(
            model_name='tooth',
            name='position_y',
            field=models.SmallIntegerField(blank=True, choices=[(0, 0), (1, 40), (2, 80), (3, 120)], null=True),
        ),
    ]
