# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 03:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0030_auto_20160301_0210'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='stroke_blue',
            field=models.BooleanField(default=False),
        ),
    ]
