# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-10 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0031_sector_stroke_blue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='circle',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='dentist',
            name='register_number',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
