# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0032_auto_20160310_0111'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
