# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0033_patient_neighborhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='derivation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
