# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-25 17:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0034_patient_derivation'),
    ]

    operations = [
        migrations.AddField(
            model_name='odontogram',
            name='month',
            field=models.CharField(choices=[('enero', 1), ('febrero', 2), ('marzo', 3), ('abril', 4), ('mayo', 5), ('junio', 6), ('julio', 7), ('agosto', 8), ('septiembre', 9), ('octubre', 10), ('noviembre', 11), ('diciembre', 12)], default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='odontogram',
            name='year',
            field=models.PositiveIntegerField(default=2016),
            preserve_default=False,
        ),
    ]
