# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0035_auto_20160325_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontogram',
            name='month',
            field=models.CharField(blank=True, choices=[('enero', 1), ('febrero', 2), ('marzo', 3), ('abril', 4), ('mayo', 5), ('junio', 6), ('julio', 7), ('agosto', 8), ('septiembre', 9), ('octubre', 10), ('noviembre', 11), ('diciembre', 12)], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='odontogram',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
