# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0036_auto_20160328_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='odontogram',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
