# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-27 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0040_patient_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='plan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
