# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0041_patient_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dni',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
