# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0042_patient_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alias',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Masculino'), (2, 'Femenino')], default=1),
        ),
    ]
