# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-10 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0044_patient_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dentist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
