# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0046_auto_20160710_0302'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='patient',
            name='preferred_day',
        ),
        migrations.AddField(
            model_name='patient',
            name='preferred_day',
            field=models.ManyToManyField(blank=True, to='person.PreferredDay'),
        ),
    ]
