# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0048_auto_20160710_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='photo',
            field=models.ImageField(default='photos/no-img.jpg', upload_to='photos/'),
        ),
    ]
