# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 07:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0049_patient_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='photo',
            new_name='picture',
        ),
    ]
