# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0050_auto_20160710_0431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(default='media/photos/no-img.jpg', upload_to='media/photos/'),
        ),
    ]
