# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-10 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0051_auto_20160710_0457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='picture',
            field=models.ImageField(default='photos/no-img.jpg', upload_to='photos/'),
        ),
    ]
