# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-06 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0053_tooth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tooth',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Ninguno'), (2, 'Realizado - Facturado'), (3, 'Realizado - No Facturado'), (4, 'No Realizado - Facturado')], default=1),
        ),
    ]
