# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bill_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
