# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-08 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20160708_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='url_file',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
