# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_bill_linode_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='url_file',
        ),
        migrations.AlterField(
            model_name='bill',
            name='linode_file',
            field=models.FileField(blank=True, null=True, upload_to=b'media/linode/'),
        ),
    ]
