# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-01 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20160801_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='linode_file',
            field=models.FileField(blank=True, null=True, upload_to=b'linode/'),
        ),
    ]
