# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-02 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160801_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_modified', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sub_index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250)),
                ('variable_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name=b'Costo variable')),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name=b'Costo fijo')),
                ('workshop_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name=b'Costo taller')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name=b'Costo total')),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name=b'Honorarios')),
                ('total_tariff', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name=b'Total arancel')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Chapter')),
            ],
        ),
    ]
