# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-11 05:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160911_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='date',
        ),
    ]
