version: "3"

services:
  db:
    image: postgres
  api:
    build:
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/odontology
    depends_on:
      - db
    command: >
      sh -c "python odontology/manage.py runserver 0.0.0.0:8000"
